[package]
name = "eravm-stable-interface"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]

[dependencies]
u256 = { package = "primitive-types", version = "0.12.1" }